var mongoose = require('mongoose');

var Schema = mongoose.Schema

var orderSchema =  new Schema({

  LogID: String,
  ProcessTime:Number,
  Revision:Number,
  Success:Boolean,
  Version:String,
  Order:{
          

    

          AllocAmt: Number,
            AllocAmtDec:Number,
            B2BOrdNum:String,
            BillCustCode: String,
            BillCustDesc:String,
            BillCustID:Number,
            BillCustInfo: String,
            BranchID:Number,
            CanadaTaxOpt: String,
            CanadaTaxOptDesc: String,
            CloseCmt:String,
            CreditCardID:String,
            CreditOverride:String,
            CreditOverrideDate:String,
            CreditOverrideEpoch:String,
            CreditOverrideFormatted:String,
            CreditOverrideTime:String,
            CreditOverrideTimeString:String,
            CreditOverrideUser:String,
            CreditOverrideUserFull:String,
            CustPONum: String,
            DaysEarly:Number,
            DropShipOpt: String,
            DropShipOptDesc: String,
            EDIOpt: String,
            EDIOptDesc: String,
            ExtraShip:String,
            FinalMsg:String,
            FreeFrtOpt: String,
            FreeFrtOptDesc: String,
            IntRef:String,
            InvoiceInfo: String,
            JobNum:String,
            MarkExp:String,
            MarkExpDate: String,
            MarkExpEpoch: Number,
            MarkExpFormatted: String,
            MarkExpTime: String,
            MarkExpTimeString: String,
            MarkExpUser: String,
            MarkExpUserFull: String,
            MiscAmt:Number,
            MiscAmtDec:Number,
            MiscAmtString: String,
            NetAmt:Number,
            NetAmtDec:Number,
            NetAmtString: String,
            OrdCreated: String,
            OrdCreatedDate: String,
            OrdCreatedEpoch: Number,
            OrdCreatedFormatted: String,
            OrdCreatedTime: String,
            OrdCreatedTimeString: String,
            OrdCreatedUser: String,
            OrdCreatedUserFull: String,
            OrdDate: String,
            OrdDisc:Number,
            OrdDiscDec:Number,
            OrdDiscPercent:Number,
            OrdDiscPercentDec:Number,
            OrdDiscPercentString: String,
            OrdDiscString: String,
            OrdFuncOpt: String,
            OrdFuncOptDesc: String,
            OrdID: String,
            OrdIDCreatedFrom:String,
            OrdIDMovedTo:String,
            OrdLvlOpt: String,
            OrdLvlOptDesc: String,
            OrdNum: String,
            OrdPackedOpt: String,
            OrdPackedOptDesc: String,
            OrdTotOnlyOpt: String,
            OrdTotOnlyOptDesc: String,
            OrdTypeOpt: String,
            OrdTypeOptDesc: String,
            OrigNetAmt: Number,
            OrigNetAmtDec:Number,
            OrigNetAmtString: String,
            OrigOrdCost: Number,
            OrigOrdCostDec:Number,
            OrigOrdCostString: String,
            OrigOrdDate: String,
            OriginOpt: String,
            OriginOptDesc:String,
            PackPrint: String,
            PackPrintDate: String,
            PackPrintEpoch: Number,
            PackPrintFormatted: String,
            PackPrintTime: String,
            PackPrintTimeString: String,
            PackPrintUser: String,
            PackPrintUserFull: String,
            PeriodicInvOpt: String,
            PeriodicInvOptDesc: String,
            PickMess:String,
            PickPrint:String,
            PickPrintDate:String,
            PickPrintEpoch:String,
            PickPrintFormatted:String,
            PickPrintTime:String,
            PickPrintTimeString:String,
            PickPrintUser:String,
            PickPrintUserFull:String,
            ProdCellID:Number,
            PromPricingOpt: String,
            PromPricingOptDesc: String,
            RecentRev: String,
            ReqDate: String,
            RevDate:String,
            ShipOpt: String,
            ShipOptDesc: String,
            ShowCofOOpt: String,
            ShowCofOOptDesc: String,
            SlsprsnCode: String,
            SlsprsnDesc: String,
            SlsprsnID:Number,
            SlsprsnInfo: String,
            SoldCustCode: String,
            SoldCustDesc:String,
            SoldCustID:Number,
            SoldCustInfo: String,
            StatusOpt: String,
            StatusOptDesc: String,
            TaxAuthCustCode: String,
            TaxAuthCustDesc: String,
            TaxAuthCustID:Number,
            TaxAuthCustInfo: String,
            TaxAuthOtherCode: String,
            TaxAuthOtherDesc: String,
            TaxAuthOtherID: Number,
            TaxAuthOtherInfo: String,
            TaxAuthRegCode: String,
            TaxAuthRegDesc: String,
            TaxAuthRegID:Number,
            TaxAuthRegInfo: String,
            TaxAuthSvcCode: String,
            TaxAuthSvcDesc: String,
            TaxAuthSvcID:Number,
            TaxAuthSvcInfo: String,
            TaxFrtOpt: String,
            TaxFrtOptDesc: String,
            TotQty: Number,
            TotQtyAlloc:Number,
            TotQtyAllocDec:Number,
            TotQtyAllocString:String,
            TotQtyBO:Number,
            TotQtyBODec:Number,
            TotQtyBOString: String,
            TotQtyDec:Number,
            TotQtyString: String,
            Address: {
                BillTo: {
                    Addr1: String,
                    Addr2:String,
                    AddrID:String,
                    BillInst:String,
                    City: String,
                    Code:Number,
                    Contact:String,
                    Country: String,
                    EDIAcct:String,
                    Fax:String,
                    Name:String,
                    Phone:String,
                    State: String,
                    Zip: String,
                },
                Contact: {
                    CellPhone:String,
                    Comment:String,
                    CtctID:String,
                    Email:String,
                    EmailInvOpt: String,
                    EmailInvOptDesc: String,
                    Ext:String,
                    Ext2:String,
                    Fax:String,
                    IMHandle:String,
                    Name:String,
                    Phone:String,
                    Phone2:String,
                    Title:String
                },
                ShipTo: {
                    Addr1: String,
                    Addr2:String,
                    AddrID:String,
                    City: String,
                    Code:Number,
                    Contact:String,
                    Country: String,
                    EDIAcct:String,
                    Fax:String,
                    FedexAcct:String,
                    Name:String,
                    Phone:String,
                    ShipInst:String,
                    State: String,
                    UPSAcct:String,
                    UPSQVNCtct:String,
                    UPSQVNEmail:String,
                    UPSQVNOpt: String,
                    UPSQVNOptDesc: String,
                    UPSQVNShipOpt: String,
                    UPSQVNShipOptDesc: String,
                    UPSQVNTypeOpt: String,
                    UPSQVNTypeOptDesc: String,
                    UPSResOpt: String,
                    UPSResOptDesc: String,
                    Zip: String,
                }
            },
            BillToCustomer: {
                APIInvOpt: String,
                APIInvOptDesc: String,
                APIPackOpt: String,
                APIPackOptDesc: String,
                APIQuoteOpt: String,
                APIQuoteOptDesc: String,
                APISalesOpt: String,
                APISalesOptDesc: String,
                ARAcctCode:String,
                ARAcctDesc:String,
                ARAcctID:String,
                ARAcctInfo:String,
                AltCustCode: String,
                AltCustDesc:String,
                AltCustID:Number,
                AltCustInfo: String,
                AltPartReqOpt: String,
                AltPartReqOptDesc: String,
                BOItemsOnPackOpt: String,
                BOItemsOnPackOptDesc: String,
                BOOrdTypeOpt: String,
                BOOrdTypeOptDesc: String,
                BillToCustCode: String,
                BillToCustDesc:String,
                BillToCustID:Number,
                BillToCustInfo: String,
                BinLblBarCodeOpt: String,
                BinLblBarCodeOptDesc: String,
                BinLblCode:String,
                BinLblHROpt: String,
                BinLblHROptDesc: String,
                BranchID:Number,
                CCAddOpt: String,
                CCAddOptDesc: String,
                CCRolodexOpt: String,
                CCRolodexOptDesc: String,
                CCVrfyOpt: String,
                CCVrfyOptDesc: String,
                CCWarnBalOpt: String,
                CCWarnBalOptDesc:String,
                CODCashCheckOpt: String,
                CODCashCheckOptDesc: String,
                CardConProf:String,
                CertAltCodeOpt: String,
                CertAltCodeOptDesc: String,
                CertSellDescOpt: String,
                CertSellDescOptDesc: String,
                CofOOrderOpt: String,
                CofOOrderOptDesc: String,
                CofOVMIOpt: String,
                CofOVMIOptDesc: String,
                CofOWorkOptDesc: String,
                ContrctCustCode: String,
                ContrctCustDesc:String,
                ContrctCustID:Number,
                ContrctCustInfo: String,
                ContrctCustLastChg:String,
                ContrctCustLastChgDate:String,
                ContrctCustLastChgEpoch:String,
                ContrctCustLastChgFormatted:String,
                ContrctCustLastChgTime:String,
                ContrctCustLastChgTimeString:String,
                ContrctCustLastChgUser:String,
                ContrctCustLastChgUserFull:String,
                CostCenterCode:String,
                CostCenterDesc:String,
                CostCenterID:String,
                CostCenterInfo:String,
                CredLimit:Number,
                CredLimitDec:Number,
                CredLimitString: String,
                CreditHold:String,
                CreditHoldDate:String,
                CreditHoldEpoch:String,
                CreditHoldFormatted:String,
                CreditHoldTime:String,
                CreditHoldTimeString:String,
                CreditHoldUser:String,
                CreditHoldUserFull:String,
                CustClassCode: String,
                CustClassDesc:String,
                CustClassID:Number,
                CustClassInfo:String,
                CustCode: String,
                CustID:Number,
                CustName:String,
                DBRate:String,
                DFARSOpt: String,
                DFARSOptDesc: String,
                DaysEarly:Number,
                DefltJob:String,
                DefltPO: String,
                Dept:String,
                DfltFormEmail:String,
                DftShipBOOpt: String,
                DftShipBOOptDesc: String,
                DropShipOpt: String,
                DropShipOptDesc: String,
                DupPOOpt: String,
                DupPOOptDesc: String,
                EDIAppCode:String,
                EDIConfCode:String,
                EDIConfDesc:String,
                EDIConfID:String,
                EDIConfInfo:String,
                EDIPackOpt: String,
                EDIPackOptDesc: String,
                EDISendNum:String,
                FOBCode:String,
                FOBDesc:String,
                FOBID:String,
                FOBInfo:String,
                Fax:String,
                FinChargeOpt: String,
                FinChargeOptDesc: String,
                GraceDays:Number,
                GraceDaysDec:Number,
                GraceDaysString: String,
                ImpOpt: String,
                ImpOptDesc: String,
                ImpOrdEmail:String,
                Init: String,
                InitDate: String,
                InitEpoch:Number,
                InitFormatted: String,
                InitTime: String,
                InitTimeString: String,
                InitUser:String,
                InitUserFull: String,
                InsSlspCode:String,
                InsSlspDesc:String,
                InsSlspID:String,
                InsSlspInfo:String,
                InvAltCodeOpt: String,
                InvAltCodeOptDesc: String,
                InvForm:String,
                InvSellDescOpt: String,
                InvSellDescOptDesc: String,
                InvSeqOpt: String,
                InvSeqOptDesc: String,
                MajorGrpOpt: String,
                MajorGrpOptDesc: String,
                MandMCBOOpt: String,
                MandMCBOOptDesc: String,
                MandMCChngOpt: String,
                MandMCChngOptDesc: String,
                MandMCDelOpt: String,
                MandMCDelOptDesc: String,
                MandMCSplitOpt: String,
                MandMCSplitOptDesc: String,
                NegAvailOpt: String,
                NegAvailOptDesc: String,
                NewOrdARSOpt: String,
                NewOrdARSOptDesc: String,
                OnTimeGrace:Number,
                OrdAltCodeOpt: String,
                OrdAltCodeOptDesc: String,
                OrdDisc:Number,
                OrdDiscDec:Number,
                OrdDiscPercent:Number,
                OrdDiscPercentDec:Number,
                OrdDiscPercentString: String,
                OrdDiscString: String,
                OrdInst:String,
                OrdSellDescOpt: String,
                OrdSellDescOptDesc: String,
                OrdShipOpt: String,
                OrdShipOptDesc: String,
                OrderAllocRuleCode:String,
                OrderAllocRuleDesc:String,
                OrderAllocRuleID:String,
                OrderAllocRuleInfo:String,
                OrderTotalOpt: String,
                OrderTotalOptDesc: String,
                OverShip: Number,
                OverShipDec:Number,
                OverShipPercent:Number,
                OverShipPercentDec:Number,
                OverShipPercentString: String,
                OverShipString: String,
                PONumReqOpt: String,
                PONumReqOptDesc: String,
                PackAltCodeOpt: String,
                PackAltCodeOptDesc: String,
                PackForm: String,
                PackInst:String,
                PackListEmail:String,
                PackPriceOpt: String,
                PackPriceOptDesc: String,
                PackSellDescOpt: String,
                PackSellDescOptDesc: String,
                PackSeqOpt: String,
                PackSeqOptDesc: String,
                PackageLblCode:String,
                PayCtct:String,
                PerInvForm:String,
                PerInvOpt: String,
                PerInvOptDesc: String,
                PerInvVMIOpt: String,
                PerInvVMIOptDesc: String,
                PerInvWOOpt: String,
                PerInvWOOptDesc: String,
                Phone:String,
                PickAltCodeOpt: String,
                PickAltCodeOptDesc: String,
                PickInst:String,
                PickSellDescOpt: String,
                PickSellDescOptDesc: String,
                PkgLblBarCodeOpt: String,
                PkgLblBarCodeOptDesc: String,
                PkgLblHROpt: String,
                PkgLblHROptDesc: String,
                PriceLvlCode: String,
                PriceLvlDesc: String,
                PromPriceFlagOpt: String,
                PromPriceFlagOptDesc: String,
                PurCtct:String,
                QuoteAltCodeOpt: String,
                QuoteAltCodeOptDesc: String,
                QuoteForm:String,
                QuoteSellDescOpt: String,
                QuoteSellDescOptDesc: String,
                QuoteSeqOpt: String,
                QuoteSeqOptDesc: String,
                RoHSOpt: String,
                RoHSOptDesc: String,
                SalesForm:String,
                SalesPriceOpt: String,
                SalesPriceOptDesc: String,
                SalesSeqOpt: String,
                SalesSeqOptDesc: String,
                SendStmtOpt: String,
                SendStmtOptDesc: String,
                ShipCtct:String,
                ShipDfltCmt:String,
                ShipLblCode:String,
                SimpleEDIOpt: String,
                SimpleEDIOptDesc: String,
                SlsprsnCode: String,
                SlsprsnDesc: String,
                SlsprsnID:Number,
                SlsprsnInfo: String,
                StmtForm:String,
                SupplierCode:String,
                VMIAllocRuleCode:String,
                VMIAllocRuleDesc:String,
                VMIAllocRuleID:Number,
                VMIAllocRuleInfo:String,
                VMIShipOpt: String,
                VMIShipOptDesc: String,
                VMISyncOpt: String,
                VMISyncOptDesc: String,
                WOShipOpt: String,
                WOShipOptDesc: String,
                WWShipLblOpt: String,
                WWShipLblOptDesc: String,
                Website:String,
                WorkAllocRuleCode:String,
                WorkAllocRuleDesc:String,
                WorkAllocRuleID:String,
                WorkAllocRuleInfo:String,
                Branch: {
                    Active: Boolean,
                    Addr1: String,
                    Addr2: String,
                    BrCode: String,
                    BrDesc: String,
                    BrName: String,
                    BranchID:Number,
                    CSZ: String,
                    Contact:String,
                    CostCenterCode:String,
                    CostCenterDesc:String,
                    CostCenterID:String,
                    CostCenterInfo:String,
                    Country: String,
                    EMail:String,
                    Fax: String,
                    LocInTransit: String,
                    LocMoveAlloc: String,
                    LocRec: String,
                    Phone: String,
                    UPSAcct:String
                }
            },
            Branch: {
                Active: Boolean,
                Addr1: String,
                Addr2: String,
                BrCode: String,
                BrDesc: String,
                BrName: String,
                BranchID:Number,
                CSZ: String,
                Contact:String,
                CostCenterCode:String,
                CostCenterDesc:String,
                CostCenterID:String,
                CostCenterInfo:String,
                Country: String,
                EMail:String,
                Fax: String,
                LocInTransit: String,
                LocMoveAlloc: String,
                LocRec: String,
                Phone: String,
                UPSAcct:String
            },
            DeliveryLog: {},
            Detail: [
                {
                    Allocated: String,
                    AllocatedDate: String,
                    AllocatedEpoch: Number,
                    AllocatedFormatted: String,
                    AllocatedTime: String,
                    AllocatedTimeString: String,
                    AllocatedUser: String,
                    AllocatedUserFull: String,
                    AllowBOOpt: String,
                    AllowBOOptDesc: String,
                    AltCode: String,
                    AltName: String,
                    BinID: Number,
                    BranchID:Number,
                    CommTotal:String,
                    CommTotalDec:Number,
                    CommTotalString: String,
                    Created: String,
                    CreatedDate: String,
                    CreatedEpoch:Number,
                    CreatedFormatted: String,
                    CreatedTime: String,
                    CreatedTimeString: String,
                    CreatedUser: String,
                    CreatedUserFull: String,
                    CtrctDtlID: Number,
                    CustCode: String,
                    CustDesc:String,
                    CustID:Number,
                    CustInfo: String,
                    DateReq: String,
                    Discount:String,
                    DiscountDec:Number,
                    DiscountPercent:String,
                    DiscountPercentDec:Number,
                    DiscountPercentString: String,
                    DiscountString: String,
                    DocPFactor: String,
                    DocPMethod: String,
                    DocPRound:Number,
                    DocQFactor: String,
                    DocQMethod: String,
                    DocQRound:Number,
                    ExtraDesc:String,
                    HistProdCode: String,
                    HistProdDesc: String,
                    HistProdID:Number,
                    IntCmt:String,
                    InvCreatedOpt: String,
                    InvCreatedOptDesc: String,
                    LineCmt: String,
                    LineNum: String,
                    OrdDate: String,
                    OrdDtlID: String,
                    OrdID: String,
                    OrdLvlOpt: String,
                    OrdLvlOptDesc: String,
                    OverShip:String,
                    OverShipDec:Number,
                    OverShipPercent:String,
                    OverShipPercentDec:Number,
                    OverShipPercentString: String,
                    OverShipString: String,
                    POLineNum:String,
                    PackCmt:String,
                    PickCmt:String,
                    PickPrint: String,
                    PickPrintDate: String,
                    PickPrintEpoch: Number,
                    PickPrintFormatted: String,
                    PickPrintTime: String,
                    PickPrintTimeString: String,
                    PickPrintUser: String,
                    PickPrintUserFull: String,
                    ProdCode: String,
                    ProdDesc: String,
                    ProdID:Number,
                    QuoteCmt:String,
                    ReqRoHSOpt: String,
                    ReqRoHSOptDesc: String,
                    SalesCmt:String,
                    SlsprsnCode: String,
                    SlsprsnDesc: String,
                    SlsprsnID:Number,
                    SlsprsnInfo: String,
                    TaxTypeOpt: String,
                    TaxTypeOptDesc: String,
                    UOMID: String,
                    Bin: {
                        AltCode: String,
                        Barcode:String,
                        BinEnabled: Boolean,
                        BinID: Number,
                        BinLoc: String,
                        CellID:Number,
                        CustID:Number,
                        ExtraBarCode:String,
                        Hold:String,
                        HoldEpoch:String,
                        HoldFormatted:String,
                        HoldTime:String,
                        HoldTimeString:String,
                        HoldUser:String,
                        HoldUserFull:String,
                        MaxQty:Number,
                        MaxQtyDec:Number,
                        MaxQtyString: String,
                        MinQty:Number,
                        MinQtyDec:Number,
                        MinQtyString: String,
                        Note1:String,
                        Note2:String,
                        POLineNum:String,
                        PONum:String,
                        PickInst:String,
                        PkgQty:Number,
                        PkgQtyDec:Number,
                        PkgQtyString: String,
                        ProdID: Number
                    },
                    More: {
                        CommTotal:String,
                        CommTotalDec:Number,
                        CommTotalString: String,
                        DiscTotal:Number,
                        DiscTotalDec:Number,
                        DiscTotalString: String,
                        ListPrice:Number,
                        ListPriceDec:Number,
                        ListPriceMethod: String,
                        ListPricePer1:Number,
                        ListPricePer1Dec:Number,
                        ListPricePer1String: String,
                        ListPriceString: String,
                        OrdTotal:Number,
                        OrdTotalDec:Number,
                        OrdTotalString: String,
                        QtyBO:Number,
                        QtyBODec:Number,
                        QtyBOStock:Number,
                        QtyBOStockDec:Number,
                        QtyBOStockString: String,
                        QtyBOString: String,
                        QtyOrd:Number,
                        QtyOrdDec:Number,
                        QtyOrdOrig:Number,
                        QtyOrdOrigDec:Number,
                        QtyOrdOrigStock:Number,
                        QtyOrdOrigStockDec:Number,
                        QtyOrdOrigStockString: String,
                        QtyOrdOrigString: String,
                        QtyOrdStock:Number,
                        QtyOrdStockDec:Number,
                        QtyOrdStockString: String,
                        QtyOrdString: String,
                        QtyShp:Number,
                        QtyShpDec:Number,
                        QtyShpStock:Number,
                        QtyShpStockDec:Number,
                        QtyShpStockString: String,
                        QtyShpString: String,
                        ShpTotal: Number,
                        ShpTotalDec:Number,
                        ShpTotalString: String,
                        StdCost: Number,
                        StdCostDec:Number,
                        StdCostMethod: String,
                        StdCostPer1:Number,
                        StdCostPer1Dec:Number,
                        StdCostPer1String: String,
                        StdCostString: String,
                        StdPrice:Number,
                        StdPriceDec:Number,
                        StdPriceMethod: String,
                        StdPricePer1:Number,
                        StdPricePer1Dec:Number,
                        StdPricePer1String: String,
                        StdPriceString: String,
                        TaxAmt: Number,
                        TaxAmtDec:Number,
                        TaxAmtString: String,
                        UnitCost:Number,
                        UnitCostDec:Number,
                        UnitCostMethod: String,
                        UnitCostPer1:Number,
                        UnitCostPer1Dec:Number,
                        UnitCostPer1String: String,
                        UnitCostString: String,
                        UnitPrice: Number,
                        UnitPriceDec:Number,
                        UnitPriceMethod: String,
                        UnitPricePer1: Number,
                        UnitPricePer1Dec:Number,
                        UnitPricePer1String: String,
                        UnitPriceString: String,
                    }
                },
                {
                    Allocated:String,
                    AllocatedDate:String,
                    AllocatedEpoch:String,
                    AllocatedFormatted:String,
                    AllocatedTime:String,
                    AllocatedTimeString:String,
                    AllocatedUser:String,
                    AllocatedUserFull:String,
                    AllowBOOpt: String,
                    AllowBOOptDesc: String,
                    AltCode: String,
                    AltName: String,
                    BinID: Number,
                    BranchID:Number,
                    CommTotal:String,
                    CommTotalDec:Number,
                    CommTotalString: String,
                    Created: String,
                    CreatedDate: String,
                    CreatedEpoch:Number,
                    CreatedFormatted: String,
                    CreatedTime: String,
                    CreatedTimeString: String,
                    CreatedUser: String,
                    CreatedUserFull: String,
                    CtrctDtlID: Number,
                    CustCode: String,
                    CustDesc:String,
                    CustID:Number,
                    CustInfo: String,
                    DateReq: String,
                    Discount:String,
                    DiscountDec:Number,
                    DiscountPercent:String,
                    DiscountPercentDec:Number,
                    DiscountPercentString: String,
                    DiscountString: String,
                    DocPFactor: String,
                    DocPMethod: String,
                    DocPRound:Number,
                    DocQFactor: String,
                    DocQMethod: String,
                    DocQRound:Number,
                    ExtraDesc:String,
                    HistProdCode: String,
                    HistProdDesc: String,
                    HistProdID: Number,
                    IntCmt:String,
                    InvCreatedOpt: String,
                    InvCreatedOptDesc: String,
                    LineCmt: String,
                    LineNum:Number,
                    OrdDate: String,
                    OrdDtlID: String,
                    OrdID: String,
                    OrdLvlOpt: String,
                    OrdLvlOptDesc: String,
                    OverShip:String,
                    OverShipDec:Number,
                    OverShipPercent:String,
                    OverShipPercentDec:Number,
                    OverShipPercentString: String,
                    OverShipString: String,
                    POLineNum:String,
                    PackCmt:String,
                    PickCmt:String,
                    PickPrint:String,
                    PickPrintDate:String,
                    PickPrintEpoch:String,
                    PickPrintFormatted:String,
                    PickPrintTime:String,
                    PickPrintTimeString:String,
                    PickPrintUser:String,
                    PickPrintUserFull:String,
                    ProdCode: String,
                    ProdDesc: String,
                    ProdID: Number,
                    QuoteCmt:String,
                    ReqRoHSOpt: String,
                    ReqRoHSOptDesc: String,
                    SalesCmt:String,
                    SlsprsnCode: String,
                    SlsprsnDesc: String,
                    SlsprsnID:Number,
                    SlsprsnInfo: String,
                    TaxTypeOpt: String,
                    TaxTypeOptDesc: String,
                    UOMID: String,
                    Bin: {
                        AltCode: String,
                        Barcode:String,
                        BinEnabled: Boolean,
                        BinID: Number,
                        BinLoc: String,
                        CellID:Number,
                        CustID:Number,
                        ExtraBarCode:String,
                        Hold:String,
                        HoldEpoch:String,
                        HoldFormatted:String,
                        HoldTime:String,
                        HoldTimeString:String,
                        HoldUser:String,
                        HoldUserFull:String,
                        MaxQty:Number,
                        MaxQtyDec:Number,
                        MaxQtyString: String,
                        MinQty:Number,
                        MinQtyDec:Number,
                        MinQtyString: String,
                        Note1:String,
                        Note2:String,
                        POLineNum:String,
                        PONum:String,
                        PickInst:String,
                        PkgQty:Number,
                        PkgQtyDec:Number,
                        PkgQtyString: String,
                        ProdID: Number
                    },
                    More: {
                        CommTotal:String,
                        CommTotalDec:Number,
                        CommTotalString: String,
                        DiscTotal:Number,
                        DiscTotalDec:Number,
                        DiscTotalString: String,
                        ListPrice:Number,
                        ListPriceDec:Number,
                        ListPriceMethod: String,
                        ListPricePer1:Number,
                        ListPricePer1Dec:Number,
                        ListPricePer1String: String,
                        ListPriceString: String,
                        OrdTotal:Number,
                        OrdTotalDec:Number,
                        OrdTotalString: String,
                        QtyBO:Number,
                        QtyBODec:Number,
                        QtyBOStock:Number,
                        QtyBOStockDec:Number,
                        QtyBOStockString: String,
                        QtyBOString: String,
                        QtyOrd:Number,
                        QtyOrdDec:Number,
                        QtyOrdOrig:Number,
                        QtyOrdOrigDec:Number,
                        QtyOrdOrigStock:Number,
                        QtyOrdOrigStockDec:Number,
                        QtyOrdOrigStockString: String,
                        QtyOrdOrigString: String,
                        QtyOrdStock:Number,
                        QtyOrdStockDec:Number,
                        QtyOrdStockString: String,
                        QtyOrdString: String,
                        QtyShp:Number,
                        QtyShpDec:Number,
                        QtyShpStock:Number,
                        QtyShpStockDec:Number,
                        QtyShpStockString: String,
                        QtyShpString: String,
                        ShpTotal:Number,
                        ShpTotalDec:Number,
                        ShpTotalString: String,
                        StdCost:Number,
                        StdCostDec:Number,
                        StdCostMethod: String,
                        StdCostPer1:Number,
                        StdCostPer1Dec:Number,
                        StdCostPer1String:String,
                        StdCostString: String,
                        StdPrice:Number,
                        StdPriceDec:Number,
                        StdPriceMethod: String,
                        StdPricePer1:Number,
                        StdPricePer1Dec:Number,
                        StdPricePer1String: String,
                        StdPriceString: String,
                        TaxAmt:Number,
                        TaxAmtDec:Number,
                        TaxAmtString: String,
                        UnitCost:Number,
                        UnitCostDec:Number,
                        UnitCostMethod: String,
                        UnitCostPer1:Number,
                        UnitCostPer1Dec:Number,
                        UnitCostPer1String:String,
                        UnitCostString: String,
                        UnitPrice:Number,
                        UnitPriceDec:Number,
                        UnitPriceMethod: String,
                        UnitPricePer1:Number,
                        UnitPricePer1Dec:Number,
                        UnitPricePer1String: String,
                        UnitPriceString: String,
                    }
                },
                {
                    Allocated: String,
                    AllocatedDate: String,
                    AllocatedEpoch: Number,
                    AllocatedFormatted: String,
                    AllocatedTime: String,
                    AllocatedTimeString: String,
                    AllocatedUser: String,
                    AllocatedUserFull: String,
                    AllowBOOpt: String,
                    AllowBOOptDesc: String,
                    AltCode: String,
                    AltName:String,
                    BinID: Number,
                    BranchID:Number,
                    CommTotal:String,
                    CommTotalDec:Number,
                    CommTotalString: String,
                    Created: String,
                    CreatedDate: String,
                    CreatedEpoch:Number,
                    CreatedFormatted: String,
                    CreatedTime: String,
                    CreatedTimeString: String,
                    CreatedUser: String,
                    CreatedUserFull: String,
                    CtrctDtlID: Number,
                    CustCode: String,
                    CustDesc:String,
                    CustID:Number,
                    CustInfo: String,
                    DateReq: String,
                    Discount:String,
                    DiscountDec:Number,
                    DiscountPercent:String,
                    DiscountPercentDec:Number,
                    DiscountPercentString: String,
                    DiscountString: String,
                    DocPFactor: String,
                    DocPMethod: String,
                    DocPRound:Number,
                    DocQFactor: String,
                    DocQMethod: String,
                    DocQRound:Number,
                    ExtraDesc:String,
                    HistProdCode: String,
                    HistProdDesc: String,
                    HistProdID:Number,
                    IntCmt:String,
                    InvCreatedOpt: String,
                    InvCreatedOptDesc: String,
                    LineCmt: String,
                    LineNum: String,
                    OrdDate: String,
                    OrdDtlID: String,
                    OrdID: String,
                    OrdLvlOpt: String,
                    OrdLvlOptDesc: String,
                    OverShip:String,
                    OverShipDec:Number,
                    OverShipPercent:String,
                    OverShipPercentDec:Number,
                    OverShipPercentString: String,
                    OverShipString: String,
                    POLineNum:String,
                    PackCmt:String,
                    PickCmt:String,
                    PickPrint: String,
                    PickPrintDate: String,
                    PickPrintEpoch:Number,
                    PickPrintFormatted: String,
                    PickPrintTime: String,
                    PickPrintTimeString: String,
                    PickPrintUser: String,
                    PickPrintUserFull: String,
                    ProdCode: String,
                    ProdDesc: String,
                    ProdID:Number,
                    QuoteCmt:String,
                    ReqRoHSOpt: String,
                    ReqRoHSOptDesc: String,
                    SalesCmt:String,
                    SlsprsnCode: String,
                    SlsprsnDesc: String,
                    SlsprsnID:Number,
                    SlsprsnInfo: String,
                    TaxTypeOpt: String,
                    TaxTypeOptDesc: String,
                    UOMID: String,
                    Bin: {
                        AltCode: String,
                        Barcode: String,
                        BinEnabled: Boolean,
                        BinID: Number,
                        BinLoc: String,
                        CellID:Number,
                        CustID:Number,
                        ExtraBarCode:String,
                        Hold:String,
                        HoldEpoch:String,
                        HoldFormatted:String,
                        HoldTime:String,
                        HoldTimeString:String,
                        HoldUser:String,
                        HoldUserFull:String,
                        MaxQty:Number,
                        MaxQtyDec:Number,
                        MaxQtyString: String,
                        MinQty:Number,
                        MinQtyDec:Number,
                        MinQtyString: String,
                        Note1:String,
                        Note2:String,
                        POLineNum:String,
                        PONum:String,
                        PickInst:String,
                        PkgQty:Number,
                        PkgQtyDec:Number,
                        PkgQtyString: String,
                        ProdID: Number
                    },
                    More: {
                        CommTotal:String,
                        CommTotalDec:Number,
                        CommTotalString: String,
                        DiscTotal:Number,
                        DiscTotalDec:Number,
                        DiscTotalString: String,
                        ListPrice:Number,
                        ListPriceDec:Number,
                        ListPriceMethod: String,
                        ListPricePer1:Number,
                        ListPricePer1Dec:Number,
                        ListPricePer1String: String,
                        ListPriceString: String,
                        OrdTotal:Number,
                        OrdTotalDec:Number,
                        OrdTotalString: String,
                        QtyBO:Number,
                        QtyBODec:Number,
                        QtyBOStock:Number,
                        QtyBOStockDec:Number,
                        QtyBOStockString: String,
                        QtyBOString: String,
                        QtyOrd:Number,
                        QtyOrdDec:Number,
                        QtyOrdOrig:Number,
                        QtyOrdOrigDec:Number,
                        QtyOrdOrigStock:Number,
                        QtyOrdOrigStockDec:Number,
                        QtyOrdOrigStockString: String,
                        QtyOrdOrigString: String,
                        QtyOrdStock:Number,
                        QtyOrdStockDec:Number,
                        QtyOrdStockString: String,
                        QtyOrdString: String,
                        QtyShp:Number,
                        QtyShpDec:Number,
                        QtyShpStock:Number,
                        QtyShpStockDec:Number,
                        QtyShpStockString: String,
                        QtyShpString: String,
                        ShpTotal:Number,
                        ShpTotalDec:Number,
                        ShpTotalString: String,
                        StdCost:Number,
                        StdCostDec:Number,
                        StdCostMethod: String,
                        StdCostPer1:Number,
                        StdCostPer1Dec:Number,
                        StdCostPer1String: String,
                        StdCostString: String,
                        StdPrice:Number,
                        StdPriceDec:Number,
                        StdPriceMethod: String,
                        StdPricePer1:Number,
                        StdPricePer1Dec:Number,
                        StdPricePer1String: String,
                        StdPriceString: String,
                        TaxAmt:Number,
                        TaxAmtDec:Number,
                        TaxAmtString: String,
                        UnitCost:Number,
                        UnitCostDec:Number,
                        UnitCostMethod: String,
                        UnitCostPer1:Number,
                        UnitCostPer1Dec:Number,
                        UnitCostPer1String: String,
                        UnitCostString: String,
                        UnitPrice:Number,
                        UnitPriceDec:Number,
                        UnitPriceMethod: String,
                        UnitPricePer1:Number,
                        UnitPricePer1Dec:Number,
                        UnitPricePer1String: String,
                        UnitPriceString:String,
                    }
                },
                {
                    Allocated: String,
                    AllocatedDate: String,
                    AllocatedEpoch: Number,
                    AllocatedFormatted: String,
                    AllocatedTime: String,
                    AllocatedTimeString:String,
                    AllocatedUser: String,
                    AllocatedUserFull: String,
                    AllowBOOpt: String,
                    AllowBOOptDesc: String,
                    AltCode: String,
                    AltName: String,
                    BinID: Number,
                    BranchID:Number,
                    CommTotal:String,
                    CommTotalDec:Number,
                    CommTotalString: String,
                    Created: String,
                    CreatedDate: String,
                    CreatedEpoch:Number,
                    CreatedFormatted: String,
                    CreatedTime: String,
                    CreatedTimeString: String,
                    CreatedUser: String,
                    CreatedUserFull: String,
                    CtrctDtlID: Number,
                    CustCode: String,
                    CustDesc:String,
                    CustID:Number,
                    CustInfo: String,
                    DateReq: String,
                    Discount:String,
                    DiscountDec:Number,
                    DiscountPercent:String,
                    DiscountPercentDec:Number,
                    DiscountPercentString: String,
                    DiscountString: String,
                    DocPFactor: String,
                    DocPMethod: String,
                    DocPRound:Number,
                    DocQFactor: String,
                    DocQMethod: String,
                    DocQRound:Number,
                    ExtraDesc:String,
                    HistProdCode: String,
                    HistProdDesc: String,
                    HistProdID: Number,
                    IntCmt:String,
                    InvCreatedOpt: String,
                    InvCreatedOptDesc: String,
                    LineCmt: String,
                    LineNum: String,
                    OrdDate: String,
                    OrdDtlID: String,
                    OrdID: String,
                    OrdLvlOpt: String,
                    OrdLvlOptDesc: String,
                    OverShip:String,
                    OverShipDec:Number,
                    OverShipPercent:String,
                    OverShipPercentDec:Number,
                    OverShipPercentString: String,
                    OverShipString: String,
                    POLineNum:String,
                    PackCmt:String,
                    PickCmt:String,
                    PickPrint: String,
                    PickPrintDate: String,
                    PickPrintEpoch: Number,
                    PickPrintFormatted: String,
                    PickPrintTime: String,
                    PickPrintTimeString: String,
                    PickPrintUser: String,
                    PickPrintUserFull: String,
                    ProdCode: String,
                    ProdDesc: String,
                    ProdID: Number,
                    QuoteCmt:String,
                    ReqRoHSOpt: String,
                    ReqRoHSOptDesc: String,
                    SalesCmt:String,
                    SlsprsnCode: String,
                    SlsprsnDesc: String,
                    SlsprsnID:Number,
                    SlsprsnInfo: String,
                    TaxTypeOpt: String,
                    TaxTypeOptDesc: String,
                    UOMID: String,
                    Bin: {
                        AltCode: String,
                        Barcode: String,
                        BinEnabled: Boolean,
                        BinID: Number,
                        BinLoc: String,
                        CellID:Number,
                        CustID:Number,
                        ExtraBarCode:String,
                        Hold:String,
                        HoldEpoch:String,
                        HoldFormatted:String,
                        HoldTime:String,
                        HoldTimeString:String,
                        HoldUser:String,
                        HoldUserFull:String,
                        MaxQty:Number,
                        MaxQtyDec:Number,
                        MaxQtyString: String,
                        MinQty:Number,
                        MinQtyDec:Number,
                        MinQtyString: String,
                        Note1:String,
                        Note2:String,
                        POLineNum:String,
                        PONum:String,
                        PickInst:String,
                        PkgQty:Number,
                        PkgQtyDec:Number,
                        PkgQtyString: String,
                        ProdID: Number
                    },
                    More: {
                        CommTotal:String,
                        CommTotalDec:Number,
                        CommTotalString: String,
                        DiscTotal:Number,
                        DiscTotalDec:Number,
                        DiscTotalString: String,
                        ListPrice:Number,
                        ListPriceDec:Number,
                        ListPriceMethod: String,
                        ListPricePer1:Number,
                        ListPricePer1Dec:Number,
                        ListPricePer1String: String,
                        ListPriceString: String,
                        OrdTotal:Number,
                        OrdTotalDec:Number,
                        OrdTotalString: String,
                        QtyBO:Number,
                        QtyBODec:Number,
                        QtyBOStock:Number,
                        QtyBOStockDec:Number,
                        QtyBOStockString: String,
                        QtyBOString: String,
                        QtyOrd:Number,
                        QtyOrdDec:Number,
                        QtyOrdOrig:Number,
                        QtyOrdOrigDec:Number,
                        QtyOrdOrigStock:Number,
                        QtyOrdOrigStockDec:Number,
                        QtyOrdOrigStockString: String,
                        QtyOrdOrigString: String,
                        QtyOrdStock:Number,
                        QtyOrdStockDec:Number,
                        QtyOrdStockString: String,
                        QtyOrdString: String,
                        QtyShp:Number,
                        QtyShpDec:Number,
                        QtyShpStock:Number,
                        QtyShpStockDec:Number,
                        QtyShpStockString: String,
                        QtyShpString: String,
                        ShpTotal:Number,
                        ShpTotalDec:Number,
                        ShpTotalString: String,
                        StdCost:Number,
                        StdCostDec:Number,
                        StdCostMethod: String,
                        StdCostPer1:Number,
                        StdCostPer1Dec:Number,
                        StdCostPer1String: String,
                        StdCostString: String,
                        StdPrice:Number,
                        StdPriceDec:Number,
                        StdPriceMethod: String,
                        StdPricePer1:Number,
                        StdPricePer1Dec:Number,
                        StdPricePer1String: String,
                        StdPriceString: String,
                        TaxAmt:Number,
                        TaxAmtDec:Number,
                        TaxAmtString: String,
                        UnitCost:Number,
                        UnitCostDec:Number,
                        UnitCostMethod: String,
                        UnitCostPer1:Number,
                        UnitCostPer1Dec:Number,
                        UnitCostPer1String: String,
                        UnitCostString: String,
                        UnitPrice:Number,
                        UnitPriceDec:Number,
                        UnitPriceMethod: String,
                        UnitPricePer1:Number,
                        UnitPricePer1Dec:Number,
                        UnitPricePer1String: String,
                        UnitPriceString:String,
                    }
                },
                {
                    Allocated: String,
                    AllocatedDate: String,
                    AllocatedEpoch: Number,
                    AllocatedFormatted: String,
                    AllocatedTime: String,
                    AllocatedTimeString: String,
                    AllocatedUser: String,
                    AllocatedUserFull: String,
                    AllowBOOpt: String,
                    AllowBOOptDesc: String,
                    AltCode: String,
                    AltName: String,
                    BinID: Number,
                    BranchID:Number,
                    CommTotal:String,
                    CommTotalDec:Number,
                    CommTotalString: String,
                    Created: String,
                    CreatedDate: String,
                    CreatedEpoch:Number,
                    CreatedFormatted: String,
                    CreatedTime: String,
                    CreatedTimeString: String,
                    CreatedUser: String,
                    CreatedUserFull: String,
                    CtrctDtlID: Number,
                    CustCode: String,
                    CustDesc:String,
                    CustID:Number,
                    CustInfo: String,
                    DateReq: String,
                    Discount:String,
                    DiscountDec:Number,
                    DiscountPercent:String,
                    DiscountPercentDec:Number,
                    DiscountPercentString: String,
                    DiscountString: String,
                    DocPFactor: String,
                    DocPMethod: String,
                    DocPRound:Number,
                    DocQFactor: String,
                    DocQMethod: String,
                    DocQRound:Number,
                    ExtraDesc:String,
                    HistProdCode: String,
                    HistProdDesc: String,
                    HistProdID:Number,
                    IntCmt:String,
                    InvCreatedOpt: String,
                    InvCreatedOptDesc: String,
                    LineCmt:String,
                    LineNum: String,
                    OrdDate: String,
                    OrdDtlID: String,
                    OrdID: String,
                    OrdLvlOpt: String,
                    OrdLvlOptDesc: String,
                    OverShip:String,
                    OverShipDec:Number,
                    OverShipPercent:String,
                    OverShipPercentDec:Number,
                    OverShipPercentString: String,
                    OverShipString: String,
                    POLineNum:String,
                    PackCmt:String,
                    PickCmt:String,
                    PickPrint: String,
                    PickPrintDate: String,
                    PickPrintEpoch:Number,
                    PickPrintFormatted: String,
                    PickPrintTime: String,
                    PickPrintTimeString: String,
                    PickPrintUser: String,
                    PickPrintUserFull: String,
                    ProdCode: String,
                    ProdDesc: String,
                    ProdID:Number,
                    QuoteCmt:String,
                    ReqRoHSOpt: String,
                    ReqRoHSOptDesc: String,
                    SalesCmt:String,
                    SlsprsnCode: String,
                    SlsprsnDesc: String,
                    SlsprsnID:Number,
                    SlsprsnInfo: String,
                    TaxTypeOpt: String,
                    TaxTypeOptDesc: String,
                    UOMID: String,
                    Bin: {
                        AltCode: String,
                        Barcode: String,
                        BinEnabled: Boolean,
                        BinID: Number,
                        BinLoc:String,
                        CellID:Number,
                        CustID:Number,
                        ExtraBarCode:String,
                        Hold:String,
                        HoldEpoch:String,
                        HoldFormatted:String,
                        HoldTime:String,
                        HoldTimeString:String,
                        HoldUser:String,
                        HoldUserFull:String,
                        MaxQty:Number,
                        MaxQtyDec:Number,
                        MaxQtyString: String,
                        MinQty:Number,
                        MinQtyDec:Number,
                        MinQtyString: String,
                        Note1:String,
                        Note2:String,
                        POLineNum:String,
                        PONum:String,
                        PickInst:String,
                        PkgQty:Number,
                        PkgQtyDec:Number,
                        PkgQtyString: String,
                        ProdID: Number
                    },
                    More: {
                        CommTotal:String,
                        CommTotalDec:Number,
                        CommTotalString: String,
                        DiscTotal:Number,
                        DiscTotalDec:Number,
                        DiscTotalString: String,
                        ListPrice:Number,
                        ListPriceDec:Number,
                        ListPriceMethod: String,
                        ListPricePer1:Number,
                        ListPricePer1Dec:Number,
                        ListPricePer1String: String,
                        ListPriceString: String,
                        OrdTotal:Number,
                        OrdTotalDec:Number,
                        OrdTotalString: String,
                        QtyBO:Number,
                        QtyBODec:Number,
                        QtyBOStock:Number,
                        QtyBOStockDec:Number,
                        QtyBOStockString: String,
                        QtyBOString: String,
                        QtyOrd:Number,
                        QtyOrdDec:Number,
                        QtyOrdOrig:Number,
                        QtyOrdOrigDec:Number,
                        QtyOrdOrigStock:Number,
                        QtyOrdOrigStockDec:Number,
                        QtyOrdOrigStockString: String,
                        QtyOrdOrigString: String,
                        QtyOrdStock:Number,
                        QtyOrdStockDec:Number,
                        QtyOrdStockString: String,
                        QtyOrdString: String,
                        QtyShp:Number,
                        QtyShpDec:Number,
                        QtyShpStock:Number,
                        QtyShpStockDec:Number,
                        QtyShpStockString: String,
                        QtyShpString: String,
                        ShpTotal: Number,
                        ShpTotalDec:Number,
                        ShpTotalString: String,
                        StdCost:Number,
                        StdCostDec:Number,
                        StdCostMethod: String,
                        StdCostPer1:Number,
                        StdCostPer1Dec:Number,
                        StdCostPer1String: String,
                        StdCostString:String,
                        StdPrice:Number,
                        StdPriceDec:Number,
                        StdPriceMethod: String,
                        StdPricePer1:Number,
                        StdPricePer1Dec:Number,
                        StdPricePer1String: String,
                        StdPriceString: String,
                        TaxAmt: Number,
                        TaxAmtDec:Number,
                        TaxAmtString: String,
                        UnitCost:Number,
                        UnitCostDec:Number,
                        UnitCostMethod: String,
                        UnitCostPer1:Number,
                        UnitCostPer1Dec:Number,
                        UnitCostPer1String: String,
                        UnitCostString:String,
                        UnitPrice:Number,
                        UnitPriceDec:Number,
                        UnitPriceMethod: String,
                        UnitPricePer1:Number,
                        UnitPricePer1Dec:Number,
                        UnitPricePer1String:String,
                        UnitPriceString: String,
                    }
                },
                {
                    Allocated: String,
                    AllocatedDate: String,
                    AllocatedEpoch: Number,
                    AllocatedFormatted: String,
                    AllocatedTime: String,
                    AllocatedTimeString: String,
                    AllocatedUser: String,
                    AllocatedUserFull: String,
                    AllowBOOpt: String,
                    AllowBOOptDesc: String,
                    AltCode: String,
                    AltName:String,
                    BinID:Number,
                    BranchID:Number,
                    CommTotal:String,
                    CommTotalDec:Number,
                    CommTotalString: String,
                    Created: String,
                    CreatedDate: String,
                    CreatedEpoch:Number,
                    CreatedFormatted: String,
                    CreatedTime: String,
                    CreatedTimeString: String,
                    CreatedUser: String,
                    CreatedUserFull: String,
                    CtrctDtlID: Number,
                    CustCode: String,
                    CustDesc:String,
                    CustID:Number,
                    CustInfo: String,
                    DateReq: String,
                    Discount:String,
                    DiscountDec:Number,
                    DiscountPercent:String,
                    DiscountPercentDec:Number,
                    DiscountPercentString: String,
                    DiscountString: String,
                    DocPFactor: String,
                    DocPMethod: String,
                    DocPRound:Number,
                    DocQFactor: String,
                    DocQMethod: String,
                    DocQRound:Number,
                    ExtraDesc:String,
                    HistProdCode: String,
                    HistProdDesc:String,
                    HistProdID:Number,
                    IntCmt:String,
                    InvCreatedOpt: String,
                    InvCreatedOptDesc: String,
                    LineCmt:String,
                    LineNum: String,
                    OrdDate: String,
                    OrdDtlID:String,
                    OrdID: String,
                    OrdLvlOpt: String,
                    OrdLvlOptDesc: String,
                    OverShip:String,
                    OverShipDec:Number,
                    OverShipPercent:String,
                    OverShipPercentDec:Number,
                    OverShipPercentString: String,
                    OverShipString: String,
                    POLineNum:String,
                    PackCmt:String,
                    PickCmt:String,
                    PickPrint: String,
                    PickPrintDate: String,
                    PickPrintEpoch:Number,
                    PickPrintFormatted: String,
                    PickPrintTime: String,
                    PickPrintTimeString: String,
                    PickPrintUser: String,
                    PickPrintUserFull: String,
                    ProdCode: String,
                    ProdDesc:String,
                    ProdID:Number,
                    QuoteCmt:String,
                    ReqRoHSOpt: String,
                    ReqRoHSOptDesc: String,
                    SalesCmt:String,
                    SlsprsnCode: String,
                    SlsprsnDesc: String,
                    SlsprsnID:Number,
                    SlsprsnInfo: String,
                    TaxTypeOpt: String,
                    TaxTypeOptDesc: String,
                    UOMID: String,
                    Bin: {
                        AltCode: String,
                        Barcode: String,
                        BinEnabled: Boolean,
                        BinID:Number,
                        BinLoc:String,
                        CellID:Number,
                        CustID:Number,
                        ExtraBarCode:String,
                        Hold:String,
                        HoldEpoch:String,
                        HoldFormatted:String,
                        HoldTime:String,
                        HoldTimeString:String,
                        HoldUser:String,
                        HoldUserFull:String,
                        MaxQty:Number,
                        MaxQtyDec:Number,
                        MaxQtyString:String,
                        MinQty:Number,
                        MinQtyDec:Number,
                        MinQtyString:String,
                        Note1:String,
                        Note2:String,
                        POLineNum:String,
                        PONum:String,
                        PickInst:String,
                        PkgQty:Number,
                        PkgQtyDec:Number,
                        PkgQtyString:String,
                        ProdID: Number
                    },
                    More: {
                        CommTotal:String,
                        CommTotalDec:Number,
                        CommTotalString: String,
                        DiscTotal:Number,
                        DiscTotalDec:Number,
                        DiscTotalString: String,
                        ListPrice:Number,
                        ListPriceDec:Number,
                        ListPriceMethod: String,
                        ListPricePer1:Number,
                        ListPricePer1Dec:Number,
                        ListPricePer1String: String,
                        ListPriceString: String,
                        OrdTotal:Number,
                        OrdTotalDec:Number,
                        OrdTotalString: String,
                        QtyBO:Number,
                        QtyBODec:Number,
                        QtyBOStock:Number,
                        QtyBOStockDec:Number,
                        QtyBOStockString: String,
                        QtyBOString: String,
                        QtyOrd:Number,
                        QtyOrdDec:Number,
                        QtyOrdOrig:Number,
                        QtyOrdOrigDec:Number,
                        QtyOrdOrigStock:Number,
                        QtyOrdOrigStockDec:Number,
                        QtyOrdOrigStockString:String,
                        QtyOrdOrigString:String,
                        QtyOrdStock:Number,
                        QtyOrdStockDec:Number,
                        QtyOrdStockString:String,
                        QtyOrdString:String,
                        QtyShp:Number,
                        QtyShpDec:Number,
                        QtyShpStock:Number,
                        QtyShpStockDec:Number,
                        QtyShpStockString:String,
                        QtyShpString:String,
                        ShpTotal: Number,
                        ShpTotalDec:Number,
                        ShpTotalString: String,
                        StdCost:Number,
                        StdCostDec:Number,
                        StdCostMethod: String,
                        StdCostPer1:Number,
                        StdCostPer1Dec:Number,
                        StdCostPer1String: String,
                        StdCostString: String,
                        StdPrice:Number,
                        StdPriceDec:Number,
                        StdPriceMethod: String,
                        StdPricePer1:Number,
                        StdPricePer1Dec:Number,
                        StdPricePer1String: String,
                        StdPriceString: String,
                        TaxAmt:Number,
                        TaxAmtDec:Number,
                        TaxAmtString:String,
                        UnitCost:Number,
                        UnitCostDec:Number,
                        UnitCostMethod: String,
                        UnitCostPer1:Number,
                        UnitCostPer1Dec:Number,
                        UnitCostPer1String: String,
                        UnitCostString: String,
                        UnitPrice:Number,
                        UnitPriceDec:Number,
                        UnitPriceMethod: String,
                        UnitPricePer1:Number,
                        UnitPricePer1Dec:Number,
                        UnitPricePer1String: String,
                        UnitPriceString: String,
                    }
                },
                {
                    Allocated: String,
                    AllocatedDate: String,
                    AllocatedEpoch: Number,
                    AllocatedFormatted: String,
                    AllocatedTime: String,
                    AllocatedTimeString: String,
                    AllocatedUser: String,
                    AllocatedUserFull: String,
                    AllowBOOpt: String,
                    AllowBOOptDesc: String,
                    AltCode: String,
                    AltName: String,
                    BinID: Number,
                    BranchID:Number,
                    CommTotal:String,
                    CommTotalDec:Number,
                    CommTotalString: String,
                    Created: String,
                    CreatedDate: String,
                    CreatedEpoch:Number,
                    CreatedFormatted: String,
                    CreatedTime: String,
                    CreatedTimeString: String,
                    CreatedUser: String,
                    CreatedUserFull: String,
                    CtrctDtlID: Number,
                    CustCode: String,
                    CustDesc:String,
                    CustID:Number,
                    CustInfo: String,
                    DateReq: String,
                    Discount:String,
                    DiscountDec:Number,
                    DiscountPercent:String,
                    DiscountPercentDec:Number,
                    DiscountPercentString: String,
                    DiscountString: String,
                    DocPFactor: String,
                    DocPMethod:String,
                    DocPRound:Number,
                    DocQFactor: String,
                    DocQMethod:String,
                    DocQRound:Number,
                    ExtraDesc:String,
                    HistProdCode:String,
                    HistProdDesc: String,
                    HistProdID:Number,
                    IntCmt:String,
                    InvCreatedOpt: String,
                    InvCreatedOptDesc: String,
                    LineCmt:String,
                    LineNum:String,
                    OrdDate: String,
                    OrdDtlID: String,
                    OrdID: String,
                    OrdLvlOpt: String,
                    OrdLvlOptDesc: String,
                    OverShip:String,
                    OverShipDec:Number,
                    OverShipPercent:String,
                    OverShipPercentDec:Number,
                    OverShipPercentString: String,
                    OverShipString: String,
                    POLineNum:String,
                    PackCmt:String,
                    PickCmt:String,
                    PickPrint: String,
                    PickPrintDate: String,
                    PickPrintEpoch:Number,
                    PickPrintFormatted: String,
                    PickPrintTime: String,
                    PickPrintTimeString: String,
                    PickPrintUser: String,
                    PickPrintUserFull: String,
                    ProdCode:String,
                    ProdDesc: String,
                    ProdID:Number,
                    QuoteCmt:String,
                    ReqRoHSOpt: String,
                    ReqRoHSOptDesc: String,
                    SalesCmt:String,
                    SlsprsnCode: String,
                    SlsprsnDesc: String,
                    SlsprsnID:Number,
                    SlsprsnInfo: String,
                    TaxTypeOpt: String,
                    TaxTypeOptDesc: String,
                    UOMID: String,
                    Bin: {
                        AltCode: String,
                        Barcode:String,
                        BinEnabled: Boolean,
                        BinID: Number,
                        BinLoc:String,
                        CellID:Number,
                        CustID:Number,
                        ExtraBarCode:String,
                        Hold:String,
                        HoldEpoch:String,
                        HoldFormatted:String,
                        HoldTime:String,
                        HoldTimeString:String,
                        HoldUser:String,
                        HoldUserFull:String,
                        MaxQty:Number,
                        MaxQtyDec:Number,
                        MaxQtyString: String,
                        MinQty:Number,
                        MinQtyDec:Number,
                        MinQtyString: String,
                        Note1:String,
                        Note2:String,
                        POLineNum:String,
                        PONum:String,
                        PickInst:String,
                        PkgQty:Number,
                        PkgQtyDec:Number,
                        PkgQtyString: String,
                        ProdID: Number
                    },
                    More: {
                        CommTotal:String,
                        CommTotalDec:Number,
                        CommTotalString: String,
                        DiscTotal:Number,
                        DiscTotalDec:Number,
                        DiscTotalString: String,
                        ListPrice:Number,
                        ListPriceDec:Number,
                        ListPriceMethod:String,
                        ListPricePer1:Number,
                        ListPricePer1Dec:Number,
                        ListPricePer1String: String,
                        ListPriceString: String,
                        OrdTotal:Number,
                        OrdTotalDec:Number,
                        OrdTotalString: String,
                        QtyBO:Number,
                        QtyBODec:Number,
                        QtyBOStock:Number,
                        QtyBOStockDec:Number,
                        QtyBOStockString: String,
                        QtyBOString: String,
                        QtyOrd:Number,
                        QtyOrdDec:Number,
                        QtyOrdOrig:Number,
                        QtyOrdOrigDec:Number,
                        QtyOrdOrigStock:Number,
                        QtyOrdOrigStockDec:Number,
                        QtyOrdOrigStockString: String,
                        QtyOrdOrigString: String,
                        QtyOrdStock:Number,
                        QtyOrdStockDec:Number,
                        QtyOrdStockString: String,
                        QtyOrdString: String,
                        QtyShp:Number,
                        QtyShpDec:Number,
                        QtyShpStock:Number,
                        QtyShpStockDec:Number,
                        QtyShpStockString: String,
                        QtyShpString: String,
                        ShpTotal: Number,
                        ShpTotalDec:Number,
                        ShpTotalString: String,
                        StdCost: Number,
                        StdCostDec:Number,
                        StdCostMethod:String,
                        StdCostPer1: Number,
                        StdCostPer1Dec:Number,
                        StdCostPer1String: String,
                        StdCostString: String,
                        StdPrice:Number,
                        StdPriceDec:Number,
                        StdPriceMethod:String,
                        StdPricePer1:Number,
                        StdPricePer1Dec:Number,
                        StdPricePer1String: String,
                        StdPriceString: String,
                        TaxAmt:Number,
                        TaxAmtDec:Number,
                        TaxAmtString:String,
                        UnitCost:Number,
                        UnitCostDec:Number,
                        UnitCostMethod:String,
                        UnitCostPer1:Number,
                        UnitCostPer1Dec:Number,
                        UnitCostPer1String: String,
                        UnitCostString: String,
                        UnitPrice:Number,
                        UnitPriceDec:Number,
                        UnitPriceMethod:String,
                        UnitPricePer1:Number,
                        UnitPricePer1Dec:Number,
                        UnitPricePer1String: String,
                        UnitPriceString: String,
                    }
                }
            ],
            PmtTerms: {
                DaysDue:String,
                Disc:Number,
                DiscDec:Number,
                DiscPercent:Number,
                DiscPercentDec:Number,
                DiscPercentString: String,
                DiscPeriod:Number,
                DiscString: String,
                DueByDay:String,
                InbyDate:String,
                SvcChgInt:Number,
                SvcChgIntDec:Number,
                SvcChgIntPercent:Number,
                SvcChgIntPercentDec:Number,
                SvcChgIntPercentString: String,
                SvcChgIntString: String,
                TermsCODOpt: String,
                TermsCODOptDesc: String,
                TermsCode: String,
                TermsCycleOpt: String,
                TermsCycleOptDesc: String,
                TermsDesc: String,
                TermsGrace:String,
                TermsTypeOpt: String,
                TermsTypeOptDesc: String,
            },
            ShipInfo: {
                BOLNum:String,
                DateShip:String,
                ExtraShip:String,
                FOBCode:String,
                FOBInfo:Number,
                FrtTerms:String,
                NumPkgs:Number,
                NumPkgsDec:Number,
                NumPkgsString: String,
                ShipAcct:String,
                ShipCollOpt: String,
                ShipCollOptDesc: String,
                ShipTPBOpt: String,
                ShipTPBOptDesc: String,
                ShipURL:String,
                ShipperID:String,
                ShipperInfo:String,
                ShipperInfoForm:String,
                TrackNum:String,
                Weight:Number,
                WeightDec:Number,
                WeightKg:Number,
                WeightKgDec:Number,
                WeightKgString: String,
                WeightString: String,
            },
            ShipTrack: [
                {
                    BOLNum:String,
                    Create: String,
                    CreateDate: String,
                    CreateEpoch: Number,
                    CreateFormatted: String,
                    CreateTime: String,
                    CreateTimeString: String,
                    CreateUser:String,
                    CreateUserFull: String,
                    CustPayFrtOpt:String,
                    CustPayFrtOptDesc:String,
                    DateShip:String,
                    FrtAmt:String,
                    FrtAmtDec:Number,
                    FrtAmtString: String,
                    NumPkgs:Number,
                    NumPkgsDec:Number,
                    NumPkgsString: String,
                    ShipperCmt:String,
                    ShipperID:String,
                    TrackNum:String,
                    Weight:String,
                    WeightDec:Number,
                    WeightKg:Number,
                    WeightKgDec:Number,
                    WeightKgString: String,
                    WeightString: String,
                    Shipper: {
                        BillOpt:String,
                        BillOptDesc:String,
                        CODOptDesc:String,
                        CustPayFrtOpt:String,
                        CustPayFrtOptDesc:String,
                        FormsOpt:String,
                        FormsOptDesc:String,
                        FrtAmt:String,
                        FrtAmtDec:Number,
                        FrtAmtString: String,
                        Phone:String,
                        SCACCode:String,
                        SCACDesc:String,
                        SCACID:String,
                        SCACInfo:String,
                        SatDelivOpt:String,
                        SatDelivOptDesc:String,
                        ShipCode:String,
                        ShipDesc:String,
                        ShipURL:String,
                        ShipperMethodCode:String,
                        ShipperMethodDesc:String,
                        ShipperMethodID:String,
                        ShipperMethodInfo:String,
                        UPSTypeOpt:String,
                        UPSTypeOptDesc:String,
                        WWPri:String
                    }
                }
            ],
            Shipment: {},
            SoldtoCustomer: {
                APIInvOpt: String,
                APIInvOptDesc: String,
                APIPackOpt: String,
                APIPackOptDesc: String,
                APIQuoteOpt: String,
                APIQuoteOptDesc: String,
                APISalesOpt: String,
                APISalesOptDesc: String,
                ARAcctCode:String,
                ARAcctDesc:String,
                ARAcctID:String,
                ARAcctInfo:String,
                AltCustCode: String,
                AltCustDesc:String,
                AltCustID:Number,
                AltCustInfo: String,
                AltPartReqOpt: String,
                AltPartReqOptDesc: String,
                BOItemsOnPackOpt: String,
                BOItemsOnPackOptDesc: String,
                BOOrdTypeOpt: String,
                BOOrdTypeOptDesc: String,
                BillToCustCode: String,
                BillToCustDesc:String,
                BillToCustID:Number,
                BillToCustInfo: String,
                BinLblBarCodeOpt: String,
                BinLblBarCodeOptDesc: String,
                BinLblCode:String,
                BinLblHROpt: String,
                BinLblHROptDesc: String,
                BranchID:Number,
                CCAddOpt: String,
                CCAddOptDesc: String,
                CCRolodexOpt: String,
                CCRolodexOptDesc: String,
                CCVrfyOpt: String,
                CCVrfyOptDesc: String,
                CCWarnBalOpt: String,
                CCWarnBalOptDesc:String,
                CODCashCheckOpt: String,
                CODCashCheckOptDesc: String,
                CardConProf:String,
                CertAltCodeOpt: String,
                CertAltCodeOptDesc: String,
                CertSellDescOpt: String,
                CertSellDescOptDesc: String,
                CofOOrderOpt: String,
                CofOOrderOptDesc: String,
                CofOVMIOpt: String,
                CofOVMIOptDesc: String,
                CofOWorkOpt: String,
                CofOWorkOptDesc: String,
                ContrctCustCode: String,
                ContrctCustDesc:String,
                ContrctCustID:Number,
                ContrctCustInfo: String,
                ContrctCustLastChg:String,
                ContrctCustLastChgDate:String,
                ContrctCustLastChgEpoch:String,
                ContrctCustLastChgFormatted:String,
                ContrctCustLastChgTime:String,
                ContrctCustLastChgTimeString:String,
                ContrctCustLastChgUser:String,
                ContrctCustLastChgUserFull:String,
                CostCenterCode:String,
                CostCenterDesc:String,
                CostCenterID:String,
                CostCenterInfo:String,
                CredLimit:Number,
                CredLimitDec:Number,
                CredLimitString: String,
                CreditHold:String,
                CreditHoldDate:String,
                CreditHoldEpoch:String,
                CreditHoldFormatted:String,
                CreditHoldTime:String,
                CreditHoldTimeString:String,
                CreditHoldUser:String,
                CreditHoldUserFull:String,
                CustClassCode: String,
                CustClassDesc:String,
                CustClassID:Number,
                CustClassInfo:String,
                CustCode: String,
                CustID:Number,
                CustName:String,
                DBRate:String,
                DFARSOpt: String,
                DFARSOptDesc: String,
                DaysEarly:Number,
                DefltJob:String,
                DefltPO: String,
                Dept:String,
                DfltFormEmail:String,
                DftShipBOOpt: String,
                DftShipBOOptDesc: String,
                DropShipOpt: String,
                DropShipOptDesc: String,
                DupPOOpt: String,
                DupPOOptDesc: String,
                EDIAppCode:String,
                EDIConfCode:String,
                EDIConfDesc:String,
                EDIConfID:String,
                EDIConfInfo:String,
                EDIPackOpt: String,
                EDIPackOptDesc: String,
                EDISendNum:String,
                FOBCode:String,
                FOBDesc:String,
                FOBID:String,
                FOBInfo:String,
                Fax:String,
                FinChargeOpt: String,
                FinChargeOptDesc: String,
                GraceDays:Number,
                GraceDaysDec:Number,
                GraceDaysString: String,
                ImpOpt: String,
                ImpOptDesc: String,
                ImpOrdEmail:String,
                Init: String,
                InitDate: String,
                InitEpoch:Number,
                InitFormatted: String,
                InitTime: String,
                InitTimeString: String,
                InitUser:String,
                InitUserFull: String,
                InsSlspCode:String,
                InsSlspDesc:String,
                InsSlspID:String,
                InsSlspInfo:String,
                InvAltCodeOpt: String,
                InvAltCodeOptDesc: String,
                InvForm:String,
                InvSellDescOpt: String,
                InvSellDescOptDesc: String,
                InvSeqOpt: String,
                InvSeqOptDesc: String,
                MajorGrpOpt: String,
                MajorGrpOptDesc: String,
                MandMCBOOpt: String,
                MandMCBOOptDesc: String,
                MandMCChngOpt: String,
                MandMCChngOptDesc: String,
                MandMCDelOpt: String,
                MandMCDelOptDesc: String,
                MandMCSplitOpt: String,
                MandMCSplitOptDesc: String,
                NegAvailOpt: String,
                NegAvailOptDesc: String,
                NewOrdARSOpt: String,
                NewOrdARSOptDesc: String,
                OnTimeGrace:Number,
                OrdAltCodeOpt: String,
                OrdAltCodeOptDesc: String,
                OrdDisc:Number,
                OrdDiscDec:Number,
                OrdDiscPercent:Number,
                OrdDiscPercentDec:Number,
                OrdDiscPercentString: String,
                OrdDiscString: String,
                OrdInst:String,
                OrdSellDescOpt: String,
                OrdSellDescOptDesc: String,
                OrdShipOpt: String,
                OrdShipOptDesc: String,
                OrderAllocRuleCode:String,
                OrderAllocRuleDesc:String,
                OrderAllocRuleID:String,
                OrderAllocRuleInfo:String,
                OrderTotalOpt: String,
                OrderTotalOptDesc: String,
                OverShip: Number,
                OverShipDec:Number,
                OverShipPercent:Number,
                OverShipPercentDec:Number,
                OverShipPercentString: String,
                OverShipString: String,
                PONumReqOpt: String,
                PONumReqOptDesc: String,
                PackAltCodeOpt: String,
                PackAltCodeOptDesc: String,
                PackForm: String,
                PackInst:String,
                PackListEmail:String,
                PackPriceOpt: String,
                PackPriceOptDesc: String,
                PackSellDescOpt: String,
                PackSellDescOptDesc: String,
                PackSeqOpt: String,
                PackSeqOptDesc: String,
                PackageLblCode:String,
                PayCtct:String,
                PerInvForm:String,
                PerInvOpt: String,
                PerInvOptDesc: String,
                PerInvVMIOpt: String,
                PerInvVMIOptDesc: String,
                PerInvWOOpt: String,
                PerInvWOOptDesc: String,
                Phone:String,
                PickAltCodeOpt: String,
                PickAltCodeOptDesc: String,
                PickInst:String,
                PickSellDescOpt: String,
                PkgLblBarCodeOpt: String,
                PkgLblBarCodeOptDesc: String,
                PkgLblHROpt: String,
                PkgLblHROptDesc: String,
                PriceLvlCode: String,
                PriceLvlDesc: String,
                PromPriceFlagOpt: String,
                PromPriceFlagOptDesc: String,
                PurCtct:String,
                QuoteAltCodeOpt: String,
                QuoteAltCodeOptDesc: String,
                QuoteForm:String,
                QuoteSellDescOpt: String,
                QuoteSellDescOptDesc: String,
                QuoteSeqOpt: String,
                QuoteSeqOptDesc: String,
                RoHSOpt: String,
                RoHSOptDesc: String,
                SalesForm:String,
                SalesPriceOpt: String,
                SalesPriceOptDesc: String,
                SalesSeqOpt: String,
                SalesSeqOptDesc: String,
                SendStmtOpt: String,
                SendStmtOptDesc: String,
                ShipCtct:String,
                ShipDfltCmt:String,
                ShipLblCode:String,
                SimpleEDIOpt: String,
                SimpleEDIOptDesc: String,
                SlsprsnCode: String,
                SlsprsnDesc: String,
                SlsprsnID:Number,
                SlsprsnInfo: String,
                StmtForm:String,
                SupplierCode:String,
                VMIAllocRuleCode:String,
                VMIAllocRuleDesc:String,
                VMIAllocRuleID:Number,
                VMIAllocRuleInfo:String,
                VMIShipOpt: String,
                VMIShipOptDesc: String,
                VMISyncOpt: String,
                VMISyncOptDesc: String,
                WOShipOpt: String,
                WOShipOptDesc: String,
                WWShipLblOpt: String,
                WWShipLblOptDesc: String,
                Website:String,
                WorkAllocRuleCode:String,
                WorkAllocRuleDesc:String,
                WorkAllocRuleID:String,
                WorkAllocRuleInfo:String,
                Branch: {
                    Active: Boolean,
                    Addr1: String,
                    Addr2: String,
                    BrCode: String,
                    BrDesc: String,
                    BrName: String,
                    BranchID:Number,
                    CSZ: String,
                    Contact:String,
                    CostCenterCode:String,
                    CostCenterDesc:String,
                    CostCenterID:String,
                    CostCenterInfo:String,
                    Country: String,
                    EMail:String,
                    Fax: String,
                    LocInTransit: String,
                    LocMoveAlloc: String,
                    LocRec: String,
                    Phone: String,
                    UPSAcct:String
                },
                CustGroup: {
                    GroupCode:String,
                    GroupDesc:String
                },
                PmtTerms: {
                    DaysDue:String,
                    Disc:Number,
                    DiscDec:Number,
                    DiscPercent:Number,
                    DiscPercentDec:Number,
                    DiscPercentString: String,
                    DiscPeriod:Number,
                    DiscString: String,
                    DueByDay:String,
                    InbyDate:String,
                    SvcChgInt:Number,
                    SvcChgIntDec:Number,
                    SvcChgIntPercent:Number,
                    SvcChgIntPercentDec:Number,
                    SvcChgIntPercentString: String,
                    SvcChgIntString: String,
                    TermsCODOpt: String,
                    TermsCODOptDesc: String,
                    TermsCode: String,
                    TermsCycleOpt: String,
                    TermsCycleOptDesc: String,
                    TermsDesc: String,
                    TermsGrace:String,
                    TermsTypeOpt: String,
                    TermsTypeOptDesc: String,
                }
            },
            ThirdPartyBill: {
                Addr1:String,
                Addr2:String,
                AddrID:String,
                City:String,
                Contact:String,
                Country:String,
                Fax:String,
                FedexAcct:String,
                Name:String,
                Phone:String,
                ShipInst:String,
                State:String,
                UPSAcct:String
            }
        




        }









});

module.exports = mongoose.model("orders", orderSchema);

